Import("env")

env.AppendUnique(
    CCFLAGS=["-std=c++17", "-fdiagnostics-color", "-Werror", "-Wall", "-Wextra"],
    CPPPATH=["#include"]
)

if env["debug"]:
    env.AppendUnique(
        CCFLAGS=["-g", "-O0"],
    )
else:
    env.AppendUnique(
        CCFLAGS=["-O3", "-flto", "-DNDEBUG"],
    )

if env["sanitize"]:
    if env["sanitize"] == "thread":
        san_list = ["thread"]
    else:
        san_list = ["address", "undefined", "leak"]

    formated_sanitizers = ["-fsanitize={}".format(san) for san in san_list]
    env.AppendUnique(
        CCFLAGS=formated_sanitizers,
    )

if env["native"]:
    env.AppendUnique(
        CCFLAGS=["-march=native"],
    )

if env["clang"]:
    env.Tool("clang")
    env.Tool("clangxx")

env.AppendUnique(LINKFLAGS=env["CCFLAGS"])

tablog_lib = env.StaticLibrary("tablog", Glob("*.cpp") + Glob("dynamic/*.cpp"))

Export("tablog_lib")
