name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt-get install -yq scons
    - name: Checkout Catch2 for encoder tests
      uses: actions/checkout@v2
      with:
        repository: catchorg/Catch2
        ref: v2.13.8
        path: catch2


    - name: Build encoder tests
      run: scons use_compilation_db=0 coverage=1 CCFLAGS=-I$GITHUB_WORKSPACE/catch2/single_include
      working-directory: encoder


    - name: Test with pytest
      run: pytest -v --cov=decoder --cov=integration_tests


    - name: Process encoder coverage
      run: gcovr -r .. --exclude "$GITHUB_WORKSPACE/catch2/" --coveralls ../encoder-coverage.json
      working-directory: encoder
    - name: Upload to Coveralls
      run: coveralls --service=github --merge encoder-coverage.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
